server:
  port: 8080
  servlet:
    context-path: /springboot_demo


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripdb?serverTimezone=UTC&characterencoding=utf-8
    username: root
    password: root

    druid:
         # 初始化连接数量
         initial-size: 5
         # 最大连接池数量
         max-active: 30
         min-idle: 5
         # 获取连接时最大等待时间，单位毫秒
         max-wait: 60000
         # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         time-between-eviction-runs-millis: 60000
         # 连接保持空闲而不被驱逐的最小时间
         min-evictable-idle-time-millis: 300000
         # 用来检测连接是否有效的sql，要求是一个查询语句
         validation-query: SELECT 1 FROM DUAL
         # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
         test-while-idle: true
         # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
         test-on-borrow: false
         # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
         test-on-return: false
         # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
         pool-prepared-statements: true
         # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
         max-pool-prepared-statement-per-connection-size: 50
         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
         filters: stat,wall,log4j2
         # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
         connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
         # 合并多个DruidDataSource的监控数据
         useGlobalDataSourceStat: true
         stat-view-servlet:
           url-pattern: /druid/*
           enabled: true # 是否启用StatFilter默认值false
         filter:
             stat:
               log-slow-sql: true
               slow-sql-millis: 1000
               merge-sql: false

             wall:
               config:
                 multi-statement-allow: true
  mvc:
    view:
      prefix: /
      suffix: .html

logging:
  file: d://logger/mylogger.log # 日志记录的文件位置
  level:
    com.chixing: debug
mybatis:
  type-aliases-package: com.chixing.entity
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql